name: AIUsageMonitor
options:
  bundleIdPrefix: com.aiusagemonitor
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.0.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

schemes:
  AIUsageMonitor:
    build:
      targets:
        AIUsageMonitor: all
        AIUsageMonitorTests: [test]
    test:
      targets:
        - AIUsageMonitorTests

targets:
  AIUsageMonitor:
    type: application
    platform: macOS
    sources:
      - path: AIUsageMonitor
    dependencies:
      - target: Shared
      - package: Sparkle
    settings:
      base:
        PRODUCT_NAME: ZonderClaudeUsage
        INFOPLIST_FILE: AIUsageMonitor/Info.plist
        CODE_SIGN_ENTITLEMENTS: AIUsageMonitor/AIUsageMonitor.entitlements
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"

  Shared:
    type: framework
    platform: macOS
    sources:
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aiusagemonitor.Shared
        INFOPLIST_FILE: Shared/Info.plist

  AIUsageMonitorTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: AIUsageMonitorTests
    dependencies:
      - target: AIUsageMonitor
      - target: Shared
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ZonderClaudeUsage.app/Contents/MacOS/ZonderClaudeUsage"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES
